### ISSUE TITLE
Select Images Do Not Fit Screen

### ISSUE THREAD

**Issue by daivat15** [SagarBM396/Bounding_Box_App#3]
When I import an image whether from gallery or camera, the complete image does not fit the screen. It looks like the image has been zoomed in. This does not happen for all images only for a few of them. I am unable to figure out any pattern. @SagarBM396 Please look into it.

**Comment by daivat15** [comment]
@SagarBM396 as an update, I am facing this issue on roughly 50% of images.

**Comment by daivat15** [comment]
@SagarBM396 I killed my other apps and loaded an image where the problem occurs multiple times. The zoom issue seems to be consistent with the image itself.

**Comment by daivat15** [comment]
@SagarBM396 after the recent commits when I import an image it gets squeezed to fit into the screen, so the aspect ratio gets changed. Is that intentional? Would it not be preferable to have the image imported with the same ratio?

**Comment by SagarBM396** [comment]
@daivat15 That is intentional. If you want to maintain aspect ratio, you may divide the height and width of the image by the same ratio instead in the rotateImage function in both Activity classes (pickImage and imageCapture)
